prefs:
  port: 4441
  https: true
  search:
  - "{context}.someapp.{customer_id}.{key}"
  - "{context}.someapp.{key}"
  storage:
    type: "mysql"
    dsn: "prefs:abc123@/prefs?charset=utf8"
    table: "prefs"
