estate:
  port: 4441
  https: true
  search:
  - "{context}.{app}.{customer_id}.{key}"
  - "{context}.{app}.{key}"
  - "{context}.{key}"
  storage:
    type: "mysql"
    dsn: "estate:abc123@/estate?charset=utf8"
    table: "estate"
