lode:
  port: 4441
  https: true
  search:
  - "{context}.{app}.{customer_id}.{key}"
  - "{context}.{app}.{key}"
  - "{context}.{key}"
  storage:
    type: "mysql"
    dsn: "lode:abc123@/lode?charset=utf8"
    table: "lode"
